### ISSUE TITLE
release classic bt memory

### ISSUE THREAD

**Issue by phatpaul** [eagi223/esp-idf_Bluetooth_Multi-Service#3]
I suggest

ESP_ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT));

should be done before initializing BLE, otherwise I ran out of RAM (4Meg RAM)

**Comment by eagi223** [comment]
Just merged your PR. Thanks! I've kind of just left this for awhile. Hopefully in the coming months I'll get to merge in a lot of the improvements that I've added from other projects.
