### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by oclyke** [eagi223/esp-idf_Bluetooth_Multi-Service#9]
@eagi223 @phatpaul, this example **really** helped clear up how to get multiple services running on the ESP32. Thanks for putting this out in the open for everyone to learn from!

(P.s. no issue! Finally settled on an issue as the best way to say thanks, feel free to close immediately)

**Comment by eagi223** [comment]
I'm glad it has helped you out! I had a really difficult time finding good resources explaining how to get multiple BLE services running on the ESP32 when I first started working with it, so I hoped this would be useful.
